# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackerNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackerNews
  
  #data
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'SwiftyJSON'
  #view
  pod 'SwiftHEXColors'
  pod 'SnapKit'
  pod 'Shimmer'

end
